version: '3'
services:
    telegram-test-bot:
        build: .
        image: telegram-test-bot
        command: telegram-test-bot
        expose:
            - "1234"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - telegram-test-bot
